config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard/index'

  root 'welcome#index'
  
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  
  scope '/dashboard' do 
    resources :properties
  end
  
  resources :dashboard 
  resources :properties
  resources :photos
  
  resources :welcome do
    collection do  
      get :property_owner
    end
  end
  
  
  

end

app/models/image_uploader.rb
class ImageUploader < CarrierWave::Uploader::Base
  include CarrierWave::MiniMagick
  storage :file

  process :resize_to_fit => [800, 800]
  
  version :thumb do
    process :resize_to_fill => [200,200]
  end
  
  def extension_white_list
    %w(jpg jpeg gif png)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :file, ImageUploader
end

app/models/property.rb
require 'carrierwave/orm/activerecord'

class Property < ActiveRecord::Base
  self.inheritance_column = "kind"
  has_many :photos
  belongs_to :user
  
  TYPES = %w| Apartment Room Condo House | 
  
  CITIES =["Cebu City",
    "Lapu-Lapu City",
    "Mandaue City",
    "Carcar City",
    "Danao City",
    "Bogo City",
    "Talisay City",
    "Naga City"]

  BEDROOMS =[
    ["Studio Type", 0],
    ["1 BR", 1],
    ["2 BR", 2],
    ["3 BR", 3],
    ["4+ BR", 4]]

  BATHROOMS =[
    ["1 BR", 1],
    ["2 BR", 2],
    ["3 BR", 3],
    ["4+ BR", 4],
    ["Shared", -1],
  ]

  def type_name
    TYPES[self.type.to_i]
  end
 end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :properties

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.name = auth.info.name   # assuming the user model has a name
      user.avatar = auth.info.image # assuming the user model has an image
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # # Prevent CSRF attacks by raising an exception.
  # # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    if request.referer == property_owner_welcome_index_url
      new_property_path
    else
      stored_location_for(resource) || request.referer || root_path
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:destroy]
  
  def destroy 
    #TODO: owner is the only who can delete the photo
    @photo.destroy
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end
end

app/controllers/properties_controller.rb
 class PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = current_user.properties.order("updated_at desc")
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    if user_signed_in? 
      @property = Property.new
    else
      redirect_to property_owner_welcome_index_path
    end
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = current_user.properties.new(property_params)

    respond_to do |format|
      if @property.save
        add_photos
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    
    respond_to do |format|
      if @property.update(property_params)
        add_photos
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
  end

  private

    def add_photos 
      if params[:property][:photos]
          params[:property][:photos].each do |p|
            photo = @property.photos.new
            photo.file = p 
            photo.save
          end
        end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = current_user.properties.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:type, :city, :address, :price, :bathrooms, :bedrooms, :description)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
   def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def property_owner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_state(controller, action) 
    "active" if current_page?(controller: controller, action: action)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/_menu.html.slim
= content_for :dashboard_menu do 
  nav class="navbar navbar-default"
    div class="container"
      div class="navbar-header"
        button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-dashboard" aria-expanded="false" aria-controls="navbar"
          span class="sr-only" Toggle navigation 
          span class="caret"

        div id="navbar-dashboard" class="navbar-collapse collapse" 
          ul class="nav navbar-nav navbar-right"
            li class=(nav_link_state("dashboard", "index"))
              = link_to "Dashboard", dashboard_index_path
            li class=(nav_link_state("properties", "index"))
              = link_to "My Properties", properties_path

app/views/dashboard/index.html.slim
#page
  h1 class="title" Dashboard
  = render partial: "dashboard/menu"

  #page-content

   

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    title = "Uberder"
    meta name="author" content="Uberder"
    meta name="description" content=""
    meta name="keywords" content=""
    meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"
    link href='http://fonts.googleapis.com/css?family=Raleway:400,600' rel='stylesheet' type='text/css'
    = csrf_meta_tags 
    = stylesheet_link_tag :application  
    = javascript_include_tag :application
  
  body
    #header
      nav class="navbar navbar-default navbar-fixed-top"
        div class="container-fluid"
          div class="navbar-header" 
            button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
              span class="sr-only" Toggle navigation 
              span class="icon-bar" 
              span class="icon-bar" 
              span class="icon-bar"
            = link_to image_tag("brand.png"), root_path, class: "navbar-brand"

          div id="navbar" class="navbar-collapse collapse" 
              ul class="nav navbar-nav navbar-right"
                li
                  = link_to new_property_path do 
                    span id="post-a-property-button" class="post-a-property btn btn-primary btn-sm"
                      = "POST A PROPERTY"
                - if user_signed_in?
                  li role="presentation" class="dropdown"
                    = link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown", "role" => "button", "aria-expanded" => "false" do 
                      = image_tag current_user.avatar, class: "img-circle", style: "width: 30px;border: 2px solid #eee;"
                      span style="margin: 0 10px;"
                        = "#{current_user.name}"
                      span class="caret"
                    ul class="dropdown-menu" role="menu"
                      li
                        = link_to "Dashboard", dashboard_index_path
                      li
                        = link_to "Sign Out", destroy_user_session_path(@current_user), method: :delete
                - else
                  
                  li
                    = link_to user_omniauth_authorize_path(:facebook) do 
                      span class="btn btn-default btn-sm" style="text-transform:uppercase;"
                        = "Join"
    
    #content
      = content_for?(:dashboard_menu) ? yield(:dashboard_menu) : ""
      = yield
      

app/views/photos/destroy.js.erb
$('#photo_<%= @photo.id %>').remove();

app/views/properties/_form.html.slim
= form_for @property, html: { multipart: true, class: "form-horizontal", style:"padding:15px" } do |f|
  .form-group
    = f.label :type, class: "col-sm-2 control-label"
      = "Type"
    .col-sm-10
      = f.select(:type, Property::TYPES, {}, { class: "form-control" })

  .form-group
    = f.label :city, class: "col-sm-2 control-label"
      = "City"
    .col-sm-10
      = f.select(:city, Property::CITIES, {}, { class: "form-control" })

  .form-group
    = f.label :address, class: "col-sm-2 control-label"
      = "Address" 
    .col-sm-10
      = f.text_field(:address, class: "form-control")

  .form-group
    = f.label :price, class: "col-sm-2 control-label"
      = "Price"
    .col-sm-10
      = f.text_field(:price, class: "form-control")     

  .form-group
    = f.label :bedrooms, class: "col-sm-2 control-label"
      = "Bedrooms"
    .col-sm-10
      = f.select(:type, Property::BEDROOMS, {}, { class: "form-control" })

  .form-group
    = f.label :bathrooms, class: "col-sm-2 control-label"
      = "Bathrooms"
    .col-sm-10
      = f.select(:type, Property::BATHROOMS, {}, { class: "form-control" })
  
  .form-group
    = f.label :description, class: "col-sm-2 control-label"
      = "Highlights"
    .col-sm-10
      = f.text_area(:description, class: "form-control", rows: "10")
  
  .form-group
    = f.label :photos, class: "col-sm-2 control-label"
      = "Photos"
    .col-sm-10
      = f.file_field :photos, multiple: true 

    .col-sm-10
      .row style="margin-top: 10px"
        - @property.photos.each do |p|
          .col-xs-6.col-md-3 id=("photo_#{p.id}")
            .thumbnail
              = link_to image_tag(p.file.versions[:thumb].url)
              .caption style="text-align: center"
                = link_to photo_path(p), method: :delete, remote: true, authenticity_token: true, data: { confirm: "Are you sure?" },  class: "btn btn-default btn-xs", type: "button" do 
                  span class="glyphicon glyphicon-remove" aria-hidden="true" 
                    = " Remove"
    
                
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/properties/destroy.js.erb
$('#property_<%= @property.id %>').remove();

app/views/properties/edit.html.slim
#page 
  = render partial: "dashboard/menu"
  h1 class="title" Edit Property


  #page-content
    = render 'form'

app/views/properties/index.html.slim
#page
  h1 class="title" 
    = "My Properties (#{@properties.count})"
  = render partial: "dashboard/menu"
  #page-content
    - @properties.each do |p|
      div id=("property_#{p.id}") class="media"
        div class="media-left"
          = link_to "#" do 
            - thumb = p.photos.first
            - url = thumb.file.versions[:thumb].url
            = image_tag url, width: "100px", class: "media-object"
        div class="media-body"
          h3 class="media-heading" 
            = "#{p.type_name} in #{p.city}"
          p
            = p.description.truncate(150)
        
        div class="media-right  media-middle"
          = link_to "Delete", property_path(p), style: "margin: 0px 5px;display:block;", method: :delete, remote: true, data: { confirm: "Are you sure?" }
          = link_to "Manage", edit_property_path(p), style: "margin: 0px 5px;display:block;"
          

     

app/views/properties/new.html.slim
#page
  h1 class="title" New Property
  = render partial: "dashboard/menu"

  #page-content
    = render 'form'

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @property.type %>
</p>

<p>
  <strong>City:</strong>
  <%= @property.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @property.bathrooms %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @property.bedrooms %>
</p>

<p>
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<% @property.photos.each do |x| %>
<%= image_tag(x.file.versions[:thumb].url) %>  
<% end %>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/welcome/index.html.slim
#hero
  div class="jumbotron"
    div class="container"
      h1 Welcome!
      p Find rooms, aparments, condos, houses for rent in Cebu.

h3 class="subtext" We are actively updating out listings. Check them out.

app/views/welcome/property_owner.html.slim
#hero
  div class="jumbotron"
    div class="container"
      h1 Rent your property today!
      p 
        = "Let's get started and we will find you tenants."
      = link_to omniauth_authorize_path("user", "facebook"), class: "btn btn-social btn-facebook btn-lg" do 
        i class="fa fa-facebook"
        = "Sign in with Facebook."
h3 class="subtext" We are actively updating out listings. Check them out.